import Head from "next/head";
import Link from "next/link";
import { useState } from "react"; // Import useState

export default function Home() {
  // Use state to manage the selected tab
  const [selectedTab, setSelectedTab] = useState("Doctor");

  return <>
    <Head>
      <title>Create T3 App</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="flex min-h-screen flex-col items-start justify-center bg-gradient-to-b from-[#6f4bbd] to-[#15162c]">
      <div className="container grid grid-cols-1 md:grid-cols-2 gap-4 px-4 py-16">
        {/* Header with "Doctor's Orders" and icon */}
        <div className="flex items-center">
          <div>
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem] ml-4">
              Doctor's Orders
            </h1>
            <p className="text-2xl text-white ml-10 mt-5">
              An apple a day...
            </p>
          </div>
        </div>

        {/* Login Box with Tabs */}
        <div className="bg-white/10 p-4 rounded-lg text-white mr-32">
          <div className="flex justify-center mb-5">
            {/* Doctor Tab */}
            <div
              className={`cursor-pointer ${
                selectedTab === "Doctor" ? "bg-white/20" : ""
              } p-3 rounded-lg mr-2`}
              onClick={() => setSelectedTab("Doctor")}
            >
              Doctor
            </div>
            {/* Patient Tab */}
            <div
              className={`cursor-pointer ${
                selectedTab === "Patient" ? "bg-white/20" : ""
              } p-3 rounded-lg`}
              onClick={() => setSelectedTab("Patient")}
            >
              Patient
            </div>
          </div>
          <h2 className="text-3xl font-semibold mb-5">
            Login as {selectedTab}
          </h2>
          <form>
            {/* Add your login form elements here */}
            <div className="mb-4">
              <label htmlFor="email" className="block text-sm font-medium">
                Email
              </label>
              <input
                type="email"
                id="email"
                name="email"
                className="mt-1 p-2 w-full text-black rounded-md border border-gray-300"
              />
            </div>
            <div className="mb-4">
              <label htmlFor="password" className="block text-sm font-medium">
                Password
              </label>
              <input
                type="password"
                id="password"
                name="password"
                className="mt-1 p-2 w-full text-black rounded-md border border-gray-300"
              />
            </div>
            <Link href="/dashboard" legacyBehavior>
              <button
                type="submit"
                className="bg-white/10 text-white px-4 py-2 rounded-md hover:bg-[#2e026d] mr-2"
              >
                Login as {selectedTab}
              </button>
            </Link>
            {/* "Forgot Password" button */}
            <button
              type="button"
              className="bg-white/10 px-2 py-1 rounded-md hover:bg-[#2e026d] mr-2"
            >
              Forgot Password
            </button>
          </form>
        </div>
      </div>
    </main>
  </>;
}
